feat: introducing table component in gnosis
epignosis/gnosis pull request #143
Opened 2023-03-22 13:09 UTC by smyrn96

## Description

Transferring Table component from TalentPLUS to gnosis design system.

2023-03-30 12:46 UTC, ThrasyvoulosKafasis requested changes

2023-03-30 12:46 UTC, ThrasyvoulosKafasis commented on src/theme/default/config/table.ts
> +  border: "#9EA5A9",
Apply colour from colours palette

2023-03-30 14:32 UTC, smyrn96 commented on src/components/Table/styles.ts
> +      border-bottom: 1px solid #dddddd;
Fixed: [7c367df](https://github.com/epignosis/gnosis/pull/143/commits/7c367dffbfda1ffbc0458b45554d8eeb674eaba7)

2023-03-31 06:51 UTC, ThrasyvoulosKafasis approved these changes

2023-03-31 06:51 UTC, ThrasyvoulosKafasis commented on src/components/Table/Table.stories.tsx
> +  sorting: { column: "code", isDescending: true },
Column "code" not exists and default sorting is not applied

2023-03-31 09:05 UTC, xanderantoniadis requested changes

2023-03-31 09:05 UTC, xanderantoniadis commented on src/components/Table/Header.tsx
> +  const handleHeaderClick = (accesor: string): void => {
handleHeaderClick doesn't depict the actual functionality of this function.
a better naming convention would be: handleColumnSort

2023-03-31 09:05 UTC, xanderantoniadis commented on src/components/Table/Header.tsx
> +  const handleCheckbox = (e: React.ChangeEvent<HTMLInputElement>): void => {
handleCheckboxClick is more descriptive of the action of this function.

2023-03-31 09:05 UTC, xanderantoniadis commented on src/components/Table/Header.tsx
> +import Cell from "./Cell";
Keep imports order right as well

2023-03-31 09:09 UTC, ThrasyvoulosKafasis commented on src/components/Table/Header.tsx
> +  const handleHeaderClick = (accesor: string): void => {
@xanderantoniadis i think that handleSortingChange would be even beter

2023-03-31 09:11 UTC, xanderantoniadis commented on src/components/Table/Header.tsx
> +  const handleHeaderClick = (accesor: string): void => {
@ThrasyvoulosKafasis sure whatever depicts the functionality better will do

2023-03-31 09:29 UTC, xanderantoniadis commented on src/components/Table/Body.tsx
> +  const [hoveredRow, setHoveredRow] = useState("");
usestate hooks should be declared first in the component

2023-03-31 09:33 UTC, xanderantoniadis commented on src/components/Table/Body.tsx
> +        <tbody>
You can remove the double tbody tag.
Instead you could move the condition (state.rows.length >0) inside the first tbody and remove the fragments(<>)

2023-03-31 09:35 UTC, xanderantoniadis commented on src/components/Table/Body.tsx
> +            const isSelected = selectedArr.includes(row.id);
selectedArr could be selectedRows

2023-03-31 09:37 UTC, xanderantoniadis commented on src/components/Table/Body.tsx
> +                key={`${row.id}-${isSelected ? "selected" : "not-selected"}`}
Keys should be unique identifiers for VDOM purposes. Just row ID would do (considering that is a unique ID).

2023-03-31 10:30 UTC, xanderantoniadis commented on src/components/Table/Body.tsx
> +                className={`${isSelected ? "selected" : ""} ${handleRowClick ? "link" : ""}`}
Create a hasLink var and evaluate there if there is a callback.
const hasLink = typeof handleRowClick === "Function";

2023-03-31 10:35 UTC, xanderantoniadis commented on src/components/Table/Body.tsx
> +                {row.actions && hoveredRow === `${row.id}` && (
I think you can do this with CSS.

Just hide the acitons container and on row hover show actions.
Its less expensive than having the ID stored everytime you enter or leave the mouse.

2023-03-31 10:51 UTC, xanderantoniadis commented on src/components/Table/Body.tsx
> +                        onClick={handleRowClick ? (): void => handleRowClick(row) : undefined}
You can set the handleRowClick a default value in the state:
handleRowClick: ()=>{}; <--- this will always return undefined.

Then you can use the handleRowClick to create conditions:
const hasClickHandler = handleRowClick() !== undefined;

2023-03-31 10:53 UTC, xanderantoniadis commented on src/components/Table/Body.tsx
> +                        onClick={handleRowClick ? (): void => handleRowClick(row) : undefined}
Also in this case you could just avoid the conditions and use:
onClick={handleRowClick(row)} <---this will return undefined if callback is not provided in the props.

2023-03-31 10:56 UTC, xanderantoniadis commented on src/components/Table/Body.tsx
> +                className={`${isSelected ? "selected" : ""} ${handleRowClick ? "link" : ""}`}
OR you can just avoid this and do what I suggested here: https://github.com/epignosis/gnosis/pull/143#discussion_r1154328585

2023-03-31 11:03 UTC, xanderantoniadis reviewed
I'm not blocking it, but I suggest most of the comments be considered :)

2023-03-31 12:27 UTC, smyrn96 commented on src/components/Table/Table.tsx
> +    case "removeAll": {
Fixed: [4723b93](https://github.com/epignosis/gnosis/pull/143/commits/4723b933893ef6e5cefa8ccd44032b3a80448750)

2023-03-31 12:27 UTC, smyrn96 commented on src/components/Table/Table.tsx
> +  | { type: "selectAll" }
Fixed: [4723b93](https://github.com/epignosis/gnosis/pull/143/commits/4723b933893ef6e5cefa8ccd44032b3a80448750)

2023-03-31 12:28 UTC, smyrn96 commented on src/components/Table/Table.tsx
> +const reducer = (state: TableState, action: Action): TableState => {
Fixed: [4723b93](https://github.com/epignosis/gnosis/pull/143/commits/4723b933893ef6e5cefa8ccd44032b3a80448750)

2023-03-31 12:28 UTC, smyrn96 commented on src/components/Table/Table.test.tsx
> +import React from "react";
Fixed: [4723b93](https://github.com/epignosis/gnosis/pull/143/commits/4723b933893ef6e5cefa8ccd44032b3a80448750)

2023-03-31 12:28 UTC, smyrn96 commented on src/components/Table/Header.tsx
> +  const handleHeaderClick = (accesor: string): void => {
Fixed: [4723b93](https://github.com/epignosis/gnosis/pull/143/commits/4723b933893ef6e5cefa8ccd44032b3a80448750)

2023-03-31 12:28 UTC, smyrn96 commented on src/components/Table/Header.tsx
> +  const handleCheckbox = (e: React.ChangeEvent<HTMLInputElement>): void => {
Fixed: [4723b93](https://github.com/epignosis/gnosis/pull/143/commits/4723b933893ef6e5cefa8ccd44032b3a80448750)

2023-03-31 12:28 UTC, smyrn96 commented on src/components/Table/Header.tsx
> +import Cell from "./Cell";
Fixed: [4723b93](https://github.com/epignosis/gnosis/pull/143/commits/4723b933893ef6e5cefa8ccd44032b3a80448750)

2023-03-31 12:28 UTC, smyrn96 commented on src/components/Table/Body.tsx
> +        <tbody>
Fixed: [4723b93](https://github.com/epignosis/gnosis/pull/143/commits/4723b933893ef6e5cefa8ccd44032b3a80448750)

2023-03-31 12:28 UTC, smyrn96 commented on src/components/Table/Body.tsx
> +            const isSelected = selectedArr.includes(row.id);
Fixed: [4723b93](https://github.com/epignosis/gnosis/pull/143/commits/4723b933893ef6e5cefa8ccd44032b3a80448750)

2023-03-31 12:28 UTC, smyrn96 commented on src/components/Table/Body.tsx
> +                key={`${row.id}-${isSelected ? "selected" : "not-selected"}`}
Fixed: [4723b93](https://github.com/epignosis/gnosis/pull/143/commits/4723b933893ef6e5cefa8ccd44032b3a80448750)

2023-03-31 12:28 UTC, smyrn96 commented on src/components/Table/Body.tsx
> +                        onClick={handleRowClick ? (): void => handleRowClick(row) : undefined}
Fixed: [4723b93](https://github.com/epignosis/gnosis/pull/143/commits/4723b933893ef6e5cefa8ccd44032b3a80448750)

2023-03-31 12:30 UTC, smyrn96 commented on src/components/Table/Body.tsx
> +                {row.actions && hoveredRow === `${row.id}` && (
I am not sure what we want here. I moved the logic at the top of the mapping.

2023-03-31 14:21 UTC, xanderantoniadis commented on src/components/Table/Body.tsx
> +                className={`${isSelectedClassname} ${hasClickHandler}`}
This doesn't make sense, I mean you should do something like this:
{hasClickHandler ? "link" : "";}

2023-03-31 14:43 UTC, xanderantoniadis commented on src/constants/Actions.ts
> +export type Action =
These are types, move them to the types.ts

2023-03-31 14:47 UTC, xanderantoniadis commented on src/components/Table/Body.tsx
> +                      <Cell key={`entry-${row.id}-${accessor}`} onClick={hasClickHandler}>
hasClickHandler is the wrong name for an event callback. Rename it to "handle*WhateverItHandles*Click"

2023-04-03 14:38 UTC, smyrn96 commented on src/components/Table/components/Cell.tsx
> +const Cell: FC<CellProps> = ({ children, as = "td", onClick, ...rest }) => {
Fixed: [6ebd91f](https://github.com/epignosis/gnosis/pull/143/commits/6ebd91f3e08a19845a0f9849d2e6689b230f063c)

2023-04-03 14:49 UTC, merged