updating color pallette
epignosis/gnosis pull request #145
Opened 2023-04-11 12:24 UTC by smyrn96

## Description

This PR is created to update the color pallete we use in Plus.

## Changes

- Dark and darker theme colors removed.
- The colors of the components have been updated.

2023-04-19 08:17 UTC, SteliosKon approved these changes

2023-04-19 08:21 UTC, smyrn96 commented on src/theme/default/colors.ts
> +//updating color pallette
Fixed: [ada76ba](https://github.com/epignosis/gnosis/pull/145/commits/ada76ba0078763616de5cb14f2be729e9001c697)

2023-04-25 11:57 UTC, ThrasyvoulosKafasis requested changes

2023-04-25 11:57 UTC, ThrasyvoulosKafasis commented on src/theme/default/config/formElements.ts
> +    background: Color(colors.red.light).alpha(0.15).string(),
src/components/FormElements/FormError/styles.ts line 8 remove hexToRGBA

2023-04-25 12:03 UTC, smyrn96 commented on src/theme/default/config/formElements.ts
> +    background: Color(colors.red.light).alpha(0.15).string(),
Fixed: [fd23ed7](https://github.com/epignosis/gnosis/pull/145/commits/fd23ed764f482768ab0c66a145e14314bddf64a5)

2023-04-25 13:34 UTC, ThrasyvoulosKafasis requested changes

2023-04-25 13:34 UTC, ThrasyvoulosKafasis commented on src/components/Table/styles.ts
> +      border-bottom: 1px solid ${hexToRGBA(colors.secondary.lightest.toString(), 0.4)};
Create a headerBorder prop in src/theme/default/config/table.ts and replace the border bottom color

2023-04-25 13:34 UTC, smyrn96 commented on src/components/Table/styles.ts
> +      border-bottom: 1px solid ${hexToRGBA(colors.secondary.lightest.toString(), 0.4)};
Fixed: [b1a3710](https://github.com/epignosis/gnosis/pull/145/commits/b1a37108b1a6dc906d78f4a47226c38dce79b78b)

2023-04-25 13:35 UTC, smyrn96 commented on src/theme/default/config/formElements.ts
> +    disabledBackground: colors.secondary.lighter,
Fixed: [b1a3710](https://github.com/epignosis/gnosis/pull/145/commits/b1a37108b1a6dc906d78f4a47226c38dce79b78b)

2023-04-25 13:39 UTC, smyrn96 commented on src/components/Table/styles.ts
> +      border-bottom: 1px solid ${hexToRGBA(colors.secondary.lightest.toString(), 0.4)};
Fixed: [0bfc9b9](https://github.com/epignosis/gnosis/pull/145/commits/0bfc9b9fbdf2f6f2929be2d5d943e3634ad2ff91)

2023-04-25 14:19 UTC, ThrasyvoulosKafasis approved these changes

2023-05-19 08:26 UTC, merged