fix: fixing some UI issues in Table component
epignosis/gnosis pull request #156
Opened 2023-06-12 11:44 UTC by smyrn96

## Description

There are some changes to be implemented in Table component.

## Changes

- Empty state will include an image followed by the text.
- Chip component that is used in filters should have an 'x' icon on hover
- Table header/row should have the same height at 54px.
- The table row should have a maximum width or ellipsis should appear.

## Fixes

ex. This PR resolves #issue1 #issue2

2023-06-13 10:41 UTC, aikaterinidis commented
@xanderantoniadis , @maryxan , @SteliosKon , @ThrasyvoulosKafasis , @lem8n this PR blocks many tasks.
Please give the highest priority on this review.

2023-06-13 11:42 UTC, SteliosKon commented on src/components/Chip/Chip.tsx
> +  const isFilterOn = Boolean(isFilter);
You don't need this extra line

2023-06-13 11:42 UTC, SteliosKon commented on src/components/Chip/styles.ts
> +        ${isFilterOn ? "display:flex" : "display:none"};
`display : ${isFilterOn : "display:flex" : "display:none"};`
 for consistency

2023-06-13 12:01 UTC, smyrn96 commented on src/components/Chip/styles.ts
> +        ${isFilterOn ? "display:flex" : "display:none"};
I am not sure I can do it that way in this ts file.

2023-06-13 12:12 UTC, smyrn96 commented on src/components/Chip/Chip.tsx
> +  const isFilterOn = Boolean(isFilter);
I need this line to get if there is or not the filter variable.

2023-06-13 12:13 UTC, smyrn96 commented on src/components/Chip/styles.ts
> +        ${isFilterOn ? "display:flex" : "display:none"};
Fixed: [4835147](https://github.com/epignosis/gnosis/pull/156/commits/48351478241389c5082c01cd75f735b45c783930)

2023-06-13 12:18 UTC, SteliosKon approved these changes
Only commented the code quality, not actually tested locally

2023-06-13 13:18 UTC, maryxan requested changes

2023-06-13 13:18 UTC, maryxan commented on src/components/Table/components/Body.tsx
> +            />
The Result component has a prop "footer". Instead of creating these new props callbackInfo, isTable and callbackFn, you can create a prop "footer" on the table emptyState, and pass it like this:

`footer: (
        <div>
          No results found with these criteria
          <br /> Please try again or
          <button>Restore to default</button> <---- Here goes your callback
        </div>
      ),`

2023-06-14 07:06 UTC, smyrn96 commented on src/components/Chip/Chip.tsx
> +  const isFilterOn = Boolean(isFilter);
Fixed: [1f07f61](https://github.com/epignosis/gnosis/pull/156/commits/1f07f617fc14dc39d978efa37eb247e6fce60f98)

2023-06-14 07:06 UTC, smyrn96 commented on src/components/Result/Result.tsx
> +          </>
Fixed: [1f07f61](https://github.com/epignosis/gnosis/pull/156/commits/1f07f617fc14dc39d978efa37eb247e6fce60f98)

2023-06-14 07:06 UTC, smyrn96 commented on src/components/Table/components/Body.tsx
> +            />
Fixed: [1f07f61](https://github.com/epignosis/gnosis/pull/156/commits/1f07f617fc14dc39d978efa37eb247e6fce60f98)

2023-06-14 07:26 UTC, xanderantoniadis commented on src/components/Table/Table.stories.tsx
> +      callbackFn: () => window.alert("Hello"),
I might be out of context but...what's this?

2023-06-14 09:31 UTC, maryxan approved these changes

2023-06-14 09:46 UTC, merged