fix: input changes
epignosis/gnosis pull request #177
Opened 2023-07-17 11:59 UTC by SteliosKon

- Added internal state to handle clear icon conditional rendering
- Added ref to handle focus issues

2023-07-18 12:40 UTC, lem8n approved these changes

2023-07-19 09:56 UTC, ThrasyvoulosKafasis requested changes

2023-07-19 09:56 UTC, ThrasyvoulosKafasis commented on src/components/FormElements/Input/Input.tsx
> +  const resetFocus = () => {
resetFocus is a little confusing name. Something like setFocus or focusInput would be more appropriate.

2023-07-19 09:56 UTC, ThrasyvoulosKafasis commented on src/components/FormElements/Input/styles.ts
> +      padding-inline-end: 5rem;
Apply less padding when input is clearable

2023-07-19 09:56 UTC, ThrasyvoulosKafasis commented on src/components/FormElements/Input/Input.stories.tsx
> +  const [state, setState] = useState("My valu");
Please remove default value

2023-07-19 11:57 UTC, SteliosKon commented on src/components/FormElements/Input/Input.tsx
> +  const resetFocus = () => {
Fixed [commit](https://github.com/epignosis/gnosis/pull/177/commits/cb6bbee19db49eae1ec9a6f410ee6a5e2e8accaf)

2023-07-19 11:57 UTC, SteliosKon commented on src/components/FormElements/Input/styles.ts
> +      padding-inline-end: 5rem;
Fixed [commit](https://github.com/epignosis/gnosis/pull/177/commits/cb6bbee19db49eae1ec9a6f410ee6a5e2e8accaf)

2023-07-19 11:57 UTC, SteliosKon commented on src/components/FormElements/Input/Input.stories.tsx
> +  const [state, setState] = useState("My valu");
Fixed [commit](https://github.com/epignosis/gnosis/pull/177/commits/cb6bbee19db49eae1ec9a6f410ee6a5e2e8accaf)

2023-07-20 09:35 UTC, merged