Feature: select update
epignosis/gnosis pull request #194
Opened 2023-08-22 10:47 UTC by SteliosKon

## Description

Introduce react-select to select reusable component

## Changes

This PR contains breaking changes

2023-08-25 10:04 UTC, ThrasyvoulosKafasis commented on src/components/FormElements/Select/components/CustomValueContainer.tsx
> +            isDisabled={selectProps.isDisabled}
isDisabled, getClassNames and innerProps are the same between SingleValue and Placeholder component. Can't be added in the common props?

2023-08-25 10:09 UTC, ThrasyvoulosKafasis requested changes

2023-08-25 10:09 UTC, ThrasyvoulosKafasis commented on src/components/FormElements/Select/styles.ts
> +const inputHeight = {
Import inputHeight from src/components/FormElements/styles.ts

2023-08-25 10:09 UTC, ThrasyvoulosKafasis commented on src/components/FormElements/Select/styles.ts
> +const optionPadding = {
Use rem

2023-08-25 11:56 UTC, SteliosKon commented on src/components/FormElements/Select/styles.ts
> +const optionPadding = {
Fixed [here](https://github.com/epignosis/gnosis/pull/194/commits/63f291f365316d8796425f9f47f7c10b228ecd02)

2023-08-25 11:56 UTC, SteliosKon commented on src/components/FormElements/Select/styles.ts
> +const inputHeight = {
Fixed [here](https://github.com/epignosis/gnosis/pull/194/commits/63f291f365316d8796425f9f47f7c10b228ecd02)

2023-08-25 12:04 UTC, SteliosKon commented on src/components/FormElements/Select/components/CustomValueContainer.tsx
> +            isDisabled={selectProps.isDisabled}
No, we cannot add them to common props. I simplified them [here](https://github.com/epignosis/gnosis/pull/194/commits/a0d11d33112d157d624c7f818f6d09512caed70b)

2023-08-28 09:06 UTC, ThrasyvoulosKafasis approved these changes

2023-08-28 09:33 UTC, merged