fix : Select component improvements
epignosis/gnosis pull request #199
Opened 2023-09-01 13:27 UTC by SteliosKon

## Description

Added improvement regarding styles.

## Changes

— Improve styles of the scroll bar
— Improve spacing to match the dropdown spacing
— Multi-select, does not close when selecting an option
— Longer options do not wrap in the following line, a 3-dot suffix appears when word exceeds the width
— Add border-radius when hovering (only on select with inner search) — Select height now is correct (same as input)

2023-09-04 12:15 UTC, ThrasyvoulosKafasis requested changes

2023-09-04 12:15 UTC, ThrasyvoulosKafasis commented on src/components/FormElements/Select/Select.tsx
> +  const indicatorSize = Number(inputHeight[size].replace("rem", "")) * 16 - 2;
You can use `calc(${inputHeight[size]} - 0.125rem)` in indicatorsContainer height prop. Also add a comment that 0.125rem is border height for future refference.

2023-09-04 12:15 UTC, ThrasyvoulosKafasis commented on src/components/FormElements/Select/styles.ts
> +      min-height: calc(${inputHeight[size]} - 2px);
Use rem

2023-09-04 12:22 UTC, SteliosKon commented on src/components/FormElements/Select/Select.tsx
> +  const indicatorSize = Number(inputHeight[size].replace("rem", "")) * 16 - 2;
Unfortunately, calc cannot be used in js files.

2023-09-04 12:22 UTC, SteliosKon commented on src/components/FormElements/Select/styles.ts
> +      min-height: calc(${inputHeight[size]} - 2px);
I used px to clearly indicate that the border is removed

2023-09-04 12:28 UTC, ThrasyvoulosKafasis commented on src/components/FormElements/Select/styles.ts
> +      min-height: calc(${inputHeight[size]} - 2px);
Leave as it is

2023-09-04 12:31 UTC, ThrasyvoulosKafasis commented on src/components/FormElements/Select/Select.tsx
> +  const indicatorSize = Number(inputHeight[size].replace("rem", "")) * 16 - 2;
The styles var is a CSSObject, so the calculation it will work.

2023-09-05 05:35 UTC, SteliosKon commented on src/components/FormElements/Select/Select.tsx
> +  const indicatorSize = Number(inputHeight[size].replace("rem", "")) * 16 - 2;
Worked [here](https://github.com/epignosis/gnosis/pull/199/commits/0a9c3a7659487179ca1f5446446da7160fc28412)

2023-09-05 06:45 UTC, ThrasyvoulosKafasis approved these changes

2023-09-05 06:48 UTC, merged