feat: Add creatable select component
epignosis/gnosis pull request #206
Opened 2023-09-12 13:15 UTC by SteliosKon

## Description

     This PR implements the Creatable Select component

2023-09-12 14:22 UTC, ThrasyvoulosKafasis requested changes

2023-09-12 14:22 UTC, ThrasyvoulosKafasis commented on src/components/FormElements/Select/CreatableSelect.tsx
> +const MAX_MENU_HEIGHT = 300;
Use constants

2023-09-12 14:22 UTC, ThrasyvoulosKafasis commented on src/components/FormElements/Select/CreatableSelect.tsx
> +const containerClassNames = (status: string, size: string) =>
Create a helper since it's use both in Select and CreatableSelect

2023-09-12 14:22 UTC, ThrasyvoulosKafasis commented on src/components/FormElements/Select/CreatableSelect.tsx
> +        <CreatableSelect
Should be always searchable to can add new options. Also inline not seems to work.

2023-09-12 14:31 UTC, SteliosKon commented on src/components/FormElements/Select/CreatableSelect.tsx
> +const MAX_MENU_HEIGHT = 300;
Updated [here](https://github.com/epignosis/gnosis/pull/206/commits/774a19887a2f6894b509829a05744c74c38c5407)

2023-09-12 14:31 UTC, SteliosKon commented on src/components/FormElements/Select/CreatableSelect.tsx
> +const containerClassNames = (status: string, size: string) =>
Updated [here](https://github.com/epignosis/gnosis/pull/206/commits/774a19887a2f6894b509829a05744c74c38c5407)

2023-09-12 14:31 UTC, SteliosKon commented on src/components/FormElements/Select/CreatableSelect.tsx
> +        <CreatableSelect
Updated [here](https://github.com/epignosis/gnosis/pull/206/commits/774a19887a2f6894b509829a05744c74c38c5407)

2023-09-13 08:37 UTC, ThrasyvoulosKafasis approved these changes

2023-09-13 12:35 UTC, ThrasyvoulosKafasis approved these changes

2023-09-13 13:36 UTC, merged