feat(dropdown): adjust menu position when there is not available space
epignosis/gnosis pull request #300
Opened 2024-02-16 11:22 UTC by SteliosKon

## Adjust menu position when there is not available space

2024-02-22 07:38 UTC, ThrasyvoulosKafasis requested changes

2024-02-22 07:38 UTC, ThrasyvoulosKafasis commented on src/components/Dropdown/Dropdown.stories.tsx
> +        <Dropdown {...args} fixPlacement placement="top-end">
`fixPlacement` and `placement` props overwrite story's controls and it's confusing that whatever you apply has no effect

2024-02-22 07:38 UTC, ThrasyvoulosKafasis commented on src/components/Dropdown/Dropdown.tsx
>  const fixPlacementMapping: Record<PlacementOptions, PlacementOptions> = {
`fixPlacementMapping` this var used for rtl direction mapping. Use a more appropriate name.

2024-02-22 07:38 UTC, ThrasyvoulosKafasis commented on src/components/Dropdown/Dropdown.tsx
> +      case "bottom-start": {
Add comments to explain the logic in each case

2024-02-26 08:33 UTC, SteliosKon commented on src/components/Dropdown/Dropdown.stories.tsx
> +        <Dropdown {...args} fixPlacement placement="top-end">
Fixed [here](https://github.com/epignosis/gnosis/pull/300/commits/5bf1ddb15b587487deb02ae29efb68c9293178c8)

2024-02-26 08:33 UTC, SteliosKon commented on src/components/Dropdown/Dropdown.tsx
> +      case "bottom-start": {
Fixed [here](https://github.com/epignosis/gnosis/pull/300/commits/5bf1ddb15b587487deb02ae29efb68c9293178c8)

2024-02-26 08:33 UTC, SteliosKon commented on src/components/Dropdown/Dropdown.tsx
>  const fixPlacementMapping: Record<PlacementOptions, PlacementOptions> = {
Fixed [here](https://github.com/epignosis/gnosis/pull/300/commits/5bf1ddb15b587487deb02ae29efb68c9293178c8)

2024-02-26 11:05 UTC, ThrasyvoulosKafasis commented on src/components/Dropdown/Dropdown.stories.tsx
> +        <Dropdown {...args} fixPlacement placement="top-end">
I can still see this issue. Fix placement is always applied as `true` and the placement is always the fixed one.

2024-02-26 12:26 UTC, merged