feat(table): implement table disable state
epignosis/gnosis pull request #303
Opened 2024-02-23 17:23 UTC by epolikrati

## Description

This PR implements the disable state of `Table` component

2024-02-26 07:16 UTC, ThrasyvoulosKafasis requested changes

2024-02-26 07:16 UTC, ThrasyvoulosKafasis commented on src/components/Table/types.ts
> +  disabled?: boolean;
Do you really have to add these props in the props type? Is seems that the table component accept all available prop for an html table.
`export type Props = ExtendableProps<HTMLAttributes<HTMLTableElement>, TableProps>;`

2024-02-27 07:50 UTC, epolikrati commented on src/components/Table/types.ts
> +  disabled?: boolean;
Indeed, the className prop is part of the HTMLAttributes, fixed it here [1e2cbf7](https://github.com/epignosis/gnosis/pull/303/commits/1e2cbf7b38fb556485a0b74a27960e89ab8e4cca). However, the disabled attribute is not applicable to <table> elements, so we will need to include it in our types.

2024-02-27 08:14 UTC, lkatmadas approved these changes

2024-03-13 09:17 UTC, lkatmadas commented on src/components/Table/components/Body.tsx
> +  disabled,
Should we set these disabled props to false by default? (the same applies in other files too)

2024-03-13 12:37 UTC, epolikrati commented on src/components/Table/components/Body.tsx
> +  disabled,
You're right. Setting the disabled props to false by default is a good practice :slightly_smiling_face: 
[4617f34](https://github.com/epignosis/gnosis/pull/303/commits/4617f34755f465b7c5d54225b1526aa91674334d)

2024-03-14 09:25 UTC, lkatmadas approved these changes

2024-03-15 07:22 UTC, ThrasyvoulosKafasis approved these changes

2024-03-15 07:26 UTC, merged