feat(breadcrumbs): add new breadcrumbs implementation
epignosis/gnosis pull request #436
Opened 2024-10-17 09:27 UTC by xanderantoniadis

[Design specs](https://app.asana.com/0/1204116037405608/1206599594779505/f)
[Figma Design](https://www.figma.com/design/1aeuMSG5ehrDd45ABt4HCr/TLMS%2B-Design-System?node-id=13654-3336&node-type=canvas&m=dev)
[Task URL](https://app.asana.com/0/1204116037405608/1208379057043842/f)
## Description
Introducing the new breadcrumbs implementation.

2024-10-22 09:41 UTC, maryxan requested changes

2024-10-22 09:41 UTC, maryxan commented on src/components/Breadcrumbs/styles.ts
> +  font-size: 0.875rem;
font-size: ${typeScaleSizes["sm"]};

2024-10-22 09:41 UTC, maryxan commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +                })}
I think its better to extract classNames on objects outside the component

2024-10-22 09:55 UTC, SteliosKon commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +  linkAriaLabel = (label) => `Breadcrumb link to ${label}`,
Possible translation issue when using text here.

2024-10-22 09:56 UTC, xanderantoniadis commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +  linkAriaLabel = (label) => `Breadcrumb link to ${label}`,
Thats just the default English value. We should define linkAriaLabel with the actual translation in the client.

2024-10-22 10:28 UTC, SteliosKon commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +  linkAriaLabel = (label) => `Breadcrumb link to ${label}`,
What if the label is in any other language besides English. Then aria label would look like this
`Breadcrumb link to बहुत परस्पर उसीएक् विभाजन हमारी ख`

2024-10-22 10:34 UTC, xanderantoniadis commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +  linkAriaLabel = (label) => `Breadcrumb link to ${label}`,
The thing is that in linkAriaLabel, you pass a function.

```
translated.text: "Breadcrumb link to "
linkAriaLabel={(label)=> `t("translated.text")} ${label}`; 
```

label will already be translated since we'll pass an items object with all translated pathnames.

2024-10-22 10:37 UTC, SteliosKon commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +  linkAriaLabel = (label) => `Breadcrumb link to ${label}`,
Ahh my bad, it is a function :)

2024-10-22 10:37 UTC, xanderantoniadis commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +  linkAriaLabel = (label) => `Breadcrumb link to ${label}`,
So in the client we'll have something like:

in translations: `breadcrumbsLink: "Breadcrumb link to "`

```
const items = [
   {label: translated reports path, href: "/reports"},
   {label: translated reports users path, href: "/reports/users"}
];

<Breadcrumbs items={items} navAriaLabel={translated_nav_aria_label} linkAriaLabel={linkAriaLabel={(label)=> `t("translated.text")} ${label}`; } />

```

2024-10-22 10:51 UTC, xanderantoniadis commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +                })}
Since this particular component doesn't have any significant amount of data to processes. This won't cause any performance issues. The benefits of having this outside the component is minimal to almost none.

I would consider this if we were about to loop hundreds of object items, but we are going to loop maximum 3 object items.

2024-10-22 10:59 UTC, xanderantoniadis commented on src/components/Breadcrumbs/styles.ts
> +  font-size: 0.875rem;
Good point! 
[Fixed here](https://github.com/epignosis/gnosis/pull/436/commits/578d9c8f48911dfd588c1714b158bbcb536e2617)

2024-10-23 08:31 UTC, maryxan approved these changes

2024-10-23 08:40 UTC, merged