[WIP] chore: add assignment icons
epignosis/gnosis pull request #63
Opened 2021-11-18 12:34 UTC by maryxan

2022-01-18 08:41 UTC, ThrasyvoulosKafasis requested changes

2022-01-18 08:41 UTC, ThrasyvoulosKafasis commented on src/components/Pagination/Pagination.tsx
> +  // console.log(current);
Remove it

2022-01-19 10:55 UTC, ThrasyvoulosKafasis approved these changes

2022-01-19 12:46 UTC, tsevdos commented
Breacing Change -> responsiveView

2022-01-20 10:09 UTC, tsevdos commented
We will add this PR to next branch to test it and then to master

2022-01-20 10:09 UTC, closed without merging