feat: add disabled functionality on Input, Textarea and Select
epignosis/gnosis pull request #87
Opened 2022-02-21 12:02 UTC by maryxan

2022-02-21 15:15 UTC, ThrasyvoulosKafasis approved these changes

2022-02-22 09:18 UTC, tsevdos requested changes

2022-02-22 09:18 UTC, tsevdos commented on src/components/FormElements/Input/Input.tsx
> +    disabled: rest.disabled,
Let's better write it like this `Boolean(rest?.disabled)`

2022-02-22 09:30 UTC, ThrasyvoulosKafasis approved these changes

2022-02-22 10:48 UTC, tsevdos approved these changes

2022-02-22 12:36 UTC, ThrasyvoulosKafasis requested changes

2022-02-22 12:36 UTC, ThrasyvoulosKafasis commented on src/components/FormElements/Select/styles.ts
> +    &,
You should remove this line

2022-02-22 12:36 UTC, ThrasyvoulosKafasis commented on src/components/FormElements/styles.ts
> +    &,
You should remove this line

2022-02-22 13:10 UTC, ThrasyvoulosKafasis approved these changes

2022-02-23 08:33 UTC, merged